'''
    An enum to label the different ticker fields yet provide the decimal value.
'''
tickerTypes = {
	"Bid Size":0,
	"Bid Price":1,
	"Ask Price":2,
	"Ask Size":3,
	"Last Price":4,
	"Last Size":5,
	"High":6,
	"Low":7,
	"Volume":8,
	"Close Price":9,
	"Bid Option Computation":10,
	"Ask Option Computation":11,
	"Last Option Computation":12,
	"Model Option Computation":13,
	"Open Tick":14,
	"Low 13 Weeks":15,
	"High 13 Weeks":16,
	"Low 26 Weeks":17,
	"High 26 Weeks":18,
	"Low 52 Weeks":19,
	"High 52 Weeks":20,
	"Average Volume":21,
	"Open Interest":22,
	"Option Historical Volatility":23,
	"Option Implied Volatility":24,
	"Option Bid Exchange":25,
	"Option Ask Exchange":26,
	"Option Call Open Interest":27,
	"Option Put Open Interest":28,
	"Option Call Volume":29,
	"Option Put Volume":30,
	"Index Future Premium":31,
	"Bid Exchange":32,
	"Ask Exchange":33,
	"Auction Volume":34,
	"Auction Price":35,
	"Auction Imbalance":36,
	"Mark Price":37,
	"Bid EFP Computation":38,
	"Ask EFP Computation":39,
	"Last EFP Computation":40,
	"Open EFP Computation":41,
	"High EFP Computation":42,
	"Low EFP Computation":43,
	"Close EFP Computation":44,
	"Last Timestamp":45,
	"Shortable":46,
	"RT Volume":48,
	"Halted":49,
	"Bid Yield":50,
	"Ask Yield":51,
	"Last Yield":52,
	"Custom Option Computation":53,
	"Trade Count":54,
	"Trade Rate":55,
	"Volume Rate":56,
	"Last RTH Trade":57,
	"RT Historical Volatility":58,
	"IB Dividends":59,
	"Bond Factor Multiplier":60,
	"Regulatory Imbalance":61,
	"News":62,
	"Short-Term Volume 3 Minutes":63,
	"Short-Term Volume 5 Minutes":64,
	"Short-Term Volume 10 Minutes":65,
	"Delayed Bid":66,
	"Delayed Ask":67,
	"Delayed Last":68,
	"Delayed Bid Size":69,
	"Delayed Ask Size":70,
	"Delayed Last Size":71,
	"Delayed High Price":72,
	"Delayed Low Price":73,
	"Delayed Volume":74,
	"Delayed Close":75,
	"Delayed Open":76,
	"RT Trade Volume":77,
	"Creditman mark price":78,
	"Creditman slow mark price":79,
	"Delayed Bid Option":80,
	"Delayed Ask Option":81,
	"Delayed Last Option":82,
	"Delayed Model Option":83,
	"Last Exchange":84,
	"Last Regulatory Time":85,
	"Futures Open Interest":86,
	"Average Option Volume":87,
	"Delayed Last Timestamp":88,
	"Shortable Shares":89,
	"ETF Nav Close":92,
	"ETF Nav Prior Close":93,
	"ETF Nav Bid":94,
	"ETF Nav Ask":95,
	"ETF Nav Last":96,
	"ETF Nav Frozen Last":97,
	"ETF Nav High":98,
	"ETF Nav Low":99,
	"Estimated IPO - Midpoint":100,
	"Final IPO Price":101,
    }

marketDataTypes = {"Live":1, "Frozen":2, "Delayed":3, "DelayedFrozen":4,}
